name: "Veolia Consumption"
version: "0.0.7"
slug: "veolia_consumption"
description: "Retrieve Veolia water consumption data"
arch:
  - amd64
  - armv7
  - armhf
startup: "application"
boot: "auto"
options:
  username: "your_email@example.com"
  password: "your_password"
schema:
  username: "str"
  password: "str"
